### ISSUE TITLE
Astar problem

### ISSUE THREAD

**Issue by YoniEnder** [AndyBobBean/PathFinding#5] opened 2021-02-06 16:19 UTC
I am using this code for a pathfinding game.
I think there is a problem with the astar algorithm. when there is a maze that has only one route, the algorithm doesn't find the solution. it add 2 neigbours and goes to one of them. then igonring the other neigbour and returning path not found.

**Comment by YoniEnder** [comment] 2021-02-06 16:24
A simple solution to this that I used was to check if the path was not found 2 times in a row. that solved it.

**Comment by AndyBobBean** [comment] 2021-02-06 21:49
Hi Yoni491, thanks for your interest in the code. I haven't looked at this code for a couple of years, so my memory is not very good - but I've been unable to replicate your problem. I generated dozens of mazes, and it seemed fine. I even hacked together a maze with only one route (picture below) and all the algorithms, including AStar worked. Do you have a seed value (the number in the programs title bar) for a maze where this problem occurs? If I can replicate the problems I can investigate fixing it.

![Capture](https://user-images.githubusercontent.com/8679323/107130399-f3514380-68c4-11eb-9b65-1bc7c67e2f9f.PNG)

**Comment by AndyBobBean** [comment] 2021-02-14 15:15
Closing as unable to reproduce issue

**Closed as completed** 2021-02-14 15:14 UTC
